name: Deploy Static Site

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.REMOTE_IP }} >> ~/.ssh/known_hosts

      - name: ÔøΩ Deploy entire repo to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/root/deploy/navydev.top/"
          strip_components: 0
          overwrite: true
          rm: true

      - name: ÔøΩüì§ Copy static files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "index.html,assets"
          target: "/var/www/navydev.top/"
          strip_components: 0
          overwrite: true

      - name: üìù Copy nginx config to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "config/nginx/conf.d/*"
          target: "/etc/nginx/conf.d/"
          strip_components: 3
          overwrite: true

      - name: üîÑ Reload nginx
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.REMOTE_IP }} << 'EOF'
            nginx -t && systemctl reload nginx
          EOF
